In [2]:
from Bio import SeqIO

records = list(
    SeqIO.parse(
        "../data/raw/BindingDBTargetSequences.fasta",
        "fasta"
    )
)

print(
    len(records)
)

11433

In [3]:
print(records[0].id)
print(records[0].description)

p1
p1 mol:protein length:376 Thymidine kinase

In [4]:
print(records[100].id)
print(records[100].description)

p151
p151 mol:protein length:99 HIV-1 Protease Mutant (Q7K/L33I/L63I) chain A

In [5]:
protein_df = pd.DataFrame({
    "Protein_ID": [r.id for r in records],
    "Description": [r.description for r in records],
    "Sequence": [str(r.seq) for r in records]
})

protein_df.head()

NameError: name 'pd' is not defined

In [ ]:
records[0]

SeqRecord(seq=Seq('MASYPCHQHASAFDQAARSRGHNNRRTALRPRRQQKATEVRLEQKMPTLLRVYI...EAN'), id='p1', name='p1', description='p1 mol:protein length:376 Thymidine kinase', dbxrefs=[])

create data frame

Sequence Length Distribution

In [ ]:
protein_df["Length"] = (
    protein_df["Sequence"]
    .apply(len)
)

protein_df["Length"].describe()

count    11433.000000
mean       595.359311
std        653.545961
min         51.000000
25%        310.000000
50%        451.000000
75%        690.000000
max      34350.000000
Name: Length, dtype: float64

In [ ]:
protein_df.to_csv(
    "../data/processed/protein_sequences.csv",
    index=False
)

In [ ]:
def encode_protein(
    seq
):

    return [
        AA_VOCAB[a]
        for a in seq
        if a in AA_VOCAB
    ]

In [ ]:
AA_VOCAB = {
    "A":0,
    "C":1,
    "D":2,
    "E":3,
    "F":4,
    "G":5,
    "H":6,
    "I":7,
    "K":8,
    "L":9,
    "M":10,
    "N":11,
    "P":12,
    "Q":13,
    "R":14,
    "S":15,
    "T":16,
    "V":17,
    "W":18,
    "Y":19
}

In [ ]:
encode_protein(
    protein_df.iloc[0]["Sequence"][:20]
)

[10, 0, 15, 19, 12, 1, 6, 13, 6, 0, 15, 0, 4, 2, 13, 0, 0, 14, 15, 14]

In [ ]:
protein_df["Length"] = (
    protein_df["Sequence"]
    .apply(len)
)

protein_df["Length"].describe()

count    11433.000000
mean       595.359311
std        653.545961
min         51.000000
25%        310.000000
50%        451.000000
75%        690.000000
max      34350.000000
Name: Length, dtype: float64

In [ ]:
protein_df["Tokens"] = (
    protein_df["Sequence"]
    .apply(encode_protein)
)

protein_df.head()

,Protein_ID,Sequence,Length,Tokens
0,p1,MASYPCHQHASAFDQAARSRGHNNRRTALRPRRQQKATEVRLEQKM...,376,"[10, 0, 15, 19, 12, 1, 6, 13, 6, 0, 15, 0, 4, ..."
1,p2,DPSKDSKAQVSAAEAGITGTWYAQLGSTFIVTAGADGALTGTYESA...,159,"[2, 12, 15, 8, 2, 15, 8, 0, 13, 17, 15, 0, 0, ..."
2,p3,DPSKDSKAQVSAAEAGITGTWYNQLGSTFIVTAGADGALTGTAESA...,159,"[2, 12, 15, 8, 2, 15, 8, 0, 13, 17, 15, 0, 0, ..."
3,p4,DPSKDSKAQVSAAEAGITGTWYNQLGATFIVTAGADGALTGTYESA...,159,"[2, 12, 15, 8, 2, 15, 8, 0, 13, 17, 15, 0, 0, ..."
4,p5,MRKIVVAAIAVSLTTVSITASASADPSKDSKAQVSAAEAGITGTWY...,183,"[10, 14, 8, 7, 17, 17, 0, 0, 7, 0, 17, 15, 9, ..."

In [ ]:
len(
    protein_df.iloc[0]["Tokens"]
)

376

In [ ]:
protein_df.iloc[0]["Tokens"][:20]

[10, 0, 15, 19, 12, 1, 6, 13, 6, 0, 15, 0, 4, 2, 13, 0, 0, 14, 15, 14]

In [ ]:
MAX_LEN = 512

def pad_sequence(tokens):

    tokens = tokens[:MAX_LEN]

    padding = [0] * (
        MAX_LEN - len(tokens)
    )

    return tokens + padding

protein_df["InputIDs"] = (
    protein_df["Tokens"]
    .apply(pad_sequence)
)

protein_df.head()

,Protein_ID,Sequence,Length,Tokens,InputIDs
0,p1,MASYPCHQHASAFDQAARSRGHNNRRTALRPRRQQKATEVRLEQKM...,376,"[10, 0, 15, 19, 12, 1, 6, 13, 6, 0, 15, 0, 4, ...","[10, 0, 15, 19, 12, 1, 6, 13, 6, 0, 15, 0, 4, ..."
1,p2,DPSKDSKAQVSAAEAGITGTWYAQLGSTFIVTAGADGALTGTYESA...,159,"[2, 12, 15, 8, 2, 15, 8, 0, 13, 17, 15, 0, 0, ...","[2, 12, 15, 8, 2, 15, 8, 0, 13, 17, 15, 0, 0, ..."
2,p3,DPSKDSKAQVSAAEAGITGTWYNQLGSTFIVTAGADGALTGTAESA...,159,"[2, 12, 15, 8, 2, 15, 8, 0, 13, 17, 15, 0, 0, ...","[2, 12, 15, 8, 2, 15, 8, 0, 13, 17, 15, 0, 0, ..."
3,p4,DPSKDSKAQVSAAEAGITGTWYNQLGATFIVTAGADGALTGTYESA...,159,"[2, 12, 15, 8, 2, 15, 8, 0, 13, 17, 15, 0, 0, ...","[2, 12, 15, 8, 2, 15, 8, 0, 13, 17, 15, 0, 0, ..."
4,p5,MRKIVVAAIAVSLTTVSITASASADPSKDSKAQVSAAEAGITGTWY...,183,"[10, 14, 8, 7, 17, 17, 0, 0, 7, 0, 17, 15, 9, ...","[10, 14, 8, 7, 17, 17, 0, 0, 7, 0, 17, 15, 9, ..."

In [ ]:
len(
    protein_df.iloc[0]["InputIDs"]
)

512

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class ProteinEncoder(nn.Module):

    def __init__(self):

        super().__init__()

        self.embedding = nn.Embedding(
            20,
            128
        )

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=128,
            nhead=8,
            batch_first=True
        )

        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=2
        )

    def forward(
        self,
        x
    ):

        x = self.embedding(x)

        x = self.transformer(x)

        return x.mean(
            dim=1
        )

In [ ]:
model = ProteinEncoder()

sample = torch.tensor(
    [
        protein_df.iloc[0]["InputIDs"]
    ]
)

output = model(sample)

print(
    output.shape
)

torch.Size([1, 128])

In [ ]:
protein_df.to_csv(
    "../data/processed/protein_sequences.csv",
    index=False
)

In [ ]:
protein_df["Target_Name"] = (
    protein_df["Description"]
    .str.replace(
        r"^p\d+\s+mol:protein\s+length:\d+\s*",
        "",
        regex=True
    )
)

protein_df[
    ["Protein_ID", "Target_Name"]
].head()

  Protein_ID         Target_Name
0         p1    Thymidine kinase
1         p2  Streptavadin(N23A)
2         p3  Streptavadin(Y43A)
3         p4  Streptavadin(S27A)
4         p5        Streptavidin

In [ ]:
protein_df["Target_Name"].sample(20)

4476                                 Endothelin-1 receptor
9152                                         Neuraminidase
10259                        ATP-dependent DNA helicase Q1
5964     Dual specificity mitogen-activated protein kin...
3971                               Melanocortin receptor 5
7318                                        Protein FAM83A
2403                     Alkanal monooxygenase alpha chain
6193           NLR family CARD domain-containing protein 4
2945                    Mitogen-activated protein kinase 3
1268                Phenylethanolamine N-methyltransferase
6938                                            E-selectin
5586                                    Beta-glucuronidase
5937                       cGMP-dependent protein kinase 2
250                   Gag-Pol polyprotein [588-1127,L687I]
9464     Pleiotropic ABC efflux transporter of multiple...
5609           Sodium channel protein type 5 subunit alpha
1564               Interleukin-17 receptor A [N206D,N265D]
8555                                 Acyl-CoA 6-desaturase
10597                                          Endoplasmin
3251                                         Amine oxidase
Name: Target_Name, dtype: str

In [ ]:
import pandas as pd

binding_df = pd.read_csv(
    "../data/processed/bindingdb_clean.csv"
)

print(binding_df.shape)
binding_df.head()

(21525, 4)

,Ligand SMILES,Target Name,Ki (nM),pKi
0,CCC(c1ccccc1)c1c(O)c2ccccc2oc1=O,Dimer of Gag-Pol polyprotein [489-587],1000.0,6.000000
1,CCC(c1ccccc1)c1c(O)cc(CCc2ccccc2)oc1=O,Dimer of Gag-Pol polyprotein [489-587],500.0,6.301030
2,CCC(Cc1ccccc1)c1cc(O)c(C(CC)c2ccccc2)c(=O)o1,Dimer of Gag-Pol polyprotein [489-587],38.0,7.420216
3,Oc1c2CCCCCCc2oc(=O)c1C(C1CC1)c1ccccc1,Dimer of Gag-Pol polyprotein [489-587],15.0,7.823909
4,CCC(Cc1ccccc1)c1cc(O)c(C(CC)c2ccccc2)c(=O)o1,Dimer of Gag-Pol polyprotein [514-612],32.0,7.494850

In [ ]:
binding_df["Target Name"].sample(20)

9357                                           Cathepsin S
20133                                 Coagulation factor X
8171                           Methionine aminopeptidase 2
13835                                 Carbonic anhydrase 4
19300                    Fatty acid-binding protein, liver
14397    Dihydroorotate dehydrogenase (quinone), mitoch...
15273                Serine/threonine-protein kinase pim-2
8080                                  Coagulation factor X
1729                            Carboxylic ester hydrolase
16595                               Cannabinoid receptor 1
6353                                     Serine protease 1
10384                      5-hydroxytryptamine receptor 2A
12841                       Carbonic anhydrase 15 [19-324]
14633                       5-hydroxytryptamine receptor 7
12614                                 Carbonic anhydrase 6
5679     Dimer of Gag-Pol polyprotein [501-599,Q508K,L5...
17569      Neuronal acetylcholine receptor subunit alpha-7
11069                                Histamine H3 receptor
10580                                           Neprilysin
21449                            Replicase polyprotein 1ab
Name: Target Name, dtype: str

In [ ]:
protein_targets = set(
    protein_df["Target_Name"]
)

binding_targets = set(
    binding_df["Target Name"]
)

matches = protein_targets.intersection(
    binding_targets
)

print("Protein Targets:", len(protein_targets))
print("Binding Targets:", len(binding_targets))
print("Exact Matches:", len(matches))

Protein Targets: 8257
Binding Targets: 771
Exact Matches: 647

In [ ]:
merged_df = binding_df.merge(
    protein_df,
    left_on="Target Name",
    right_on="Target_Name",
    how="inner"
)

print(merged_df.shape)

(94610, 8)

In [ ]:
merged_df[
    [
        "Ligand SMILES",
        "Target Name",
        "pKi"
    ]
].head()

                      Ligand SMILES                     Target Name       pKi
0  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc12  5-hydroxytryptamine receptor 7  6.318759
1  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc12  5-hydroxytryptamine receptor 7  6.318759
2  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc12  5-hydroxytryptamine receptor 7  6.318759
3  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc12  5-hydroxytryptamine receptor 7  6.318759
4  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc12  5-hydroxytryptamine receptor 7  6.318759

In [ ]:
merged_df.columns

Index(['Ligand SMILES', 'Target Name', 'Ki (nM)', 'pKi', 'Protein_ID',
       'Description', 'Sequence', 'Target_Name'],
      dtype='str')

In [ ]:
merged_df.to_csv(
    "../data/processed/drug_protein_dataset.csv",
    index=False
)

In [ ]:
merged_df[
    [
        "Ligand SMILES",
        "Target Name",
        "pKi"
    ]
].head()

                      Ligand SMILES                     Target Name       pKi
0  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc12  5-hydroxytryptamine receptor 7  6.318759
1  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc12  5-hydroxytryptamine receptor 7  6.318759
2  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc12  5-hydroxytryptamine receptor 7  6.318759
3  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc12  5-hydroxytryptamine receptor 7  6.318759
4  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc12  5-hydroxytryptamine receptor 7  6.318759

In [ ]:
merged_df["pKi"].describe()

count    94610.000000
mean         6.507805
std          1.607843
min         -0.000000
25%          5.481486
50%          6.546162
75%          7.602060
max         12.698970
Name: pKi, dtype: float64

In [ ]:
merged_df["Target Name"].nunique()

647

In [7]:
import pandas as pd

binding_df = pd.read_csv(
    "../data/processed/bindingdb_clean.csv"
)

protein_df = pd.read_csv(
    "../data/processed/protein_sequences.csv"
)

In [8]:
protein_df["Target_Name"] = (
    protein_df["Description"]
    .str.replace(
        r"^p\d+\s+mol:protein\s+length:\d+\s*",
        "",
        regex=True
    )
)

In [9]:
merged_df = binding_df.merge(
    protein_df,
    left_on="Target Name",
    right_on="Target_Name",
    how="inner"
)

print(merged_df.shape)

(94610, 8)

In [10]:
merged_df.to_csv(
    "../data/processed/drug_protein_dataset.csv",
    index=False
)

In [11]:
df = pd.read_csv(
    "../data/processed/drug_protein_dataset.csv"
)

print(df.shape)
print(df.columns)

(94610, 8)
Index(['Ligand SMILES', 'Target Name', 'Ki (nM)', 'pKi', 'Protein_ID',
       'Description', 'Sequence', 'Target_Name'],
      dtype='str')

In [12]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42
)

print(train_df.shape)
print(test_df.shape)

(75688, 8)
(18922, 8)

In [13]:
AA_VOCAB = {
    "A":0,
    "C":1,
    "D":2,
    "E":3,
    "F":4,
    "G":5,
    "H":6,
    "I":7,
    "K":8,
    "L":9,
    "M":10,
    "N":11,
    "P":12,
    "Q":13,
    "R":14,
    "S":15,
    "T":16,
    "V":17,
    "W":18,
    "Y":19
}

In [14]:
MAX_LEN = 512

def encode_protein(seq):

    tokens = [
        AA_VOCAB[a]
        for a in seq
        if a in AA_VOCAB
    ]

    tokens = tokens[:MAX_LEN]

    tokens += [0] * (
        MAX_LEN - len(tokens)
    )

    return tokens

In [15]:
sample_df = train_df.sample(
    5000,
    random_state=42
).reset_index(drop=True)

sample_df["ProteinTokens"] = (
    sample_df["Sequence"]
    .apply(encode_protein)
)

sample_df.head()

,Ligand SMILES,Target Name,Ki (nM),pKi,Protein_ID,Description,Sequence,Target_Name,ProteinTokens
0,NS(=O)(=O)c1nnc(s1)-c1ccccc1Cl,Carbonic anhydrase 2,12.0,7.920819,p50000479,p50000479 mol:protein length:260 Carbonic anhy...,MSHHWGYSKSNGPENWHKEFPIANGDRQSPVDIDTGTAQHDPSLQP...,Carbonic anhydrase 2,"[10, 15, 6, 6, 18, 5, 19, 15, 8, 15, 11, 5, 12..."
1,CCCC(=N)NCCC[C@H](N)C(O)=O |r|,"Nitric oxide synthase, inducible",8610.0,5.064997,p2225,p2225 mol:protein length:1144 Nitric oxide syn...,MACPWKFLFKVKSYQSDLKEEKDINNNVKKTPCAVLSPTIQDDPKS...,"Nitric oxide synthase, inducible","[10, 0, 1, 12, 18, 8, 4, 9, 4, 8, 17, 8, 15, 1..."
2,O=n1ccccc1S[Zn]Sc1ccccn1=O,Replicase polyprotein 1ab,170.0,6.769551,p801,p801 mol:protein length:6629 Replicase polypro...,MASSLKQGVSPKPRDVILVSKDIPEQLCDALFFYTSHNPKDYADAF...,Replicase polyprotein 1ab,"[10, 0, 15, 15, 9, 8, 13, 5, 17, 15, 12, 8, 12..."
3,CC(C)c1cc(c(C)cc1O)C1(OC(=O)c2ccc3ccccc3c12)c1...,Dihydrofolate reductase,13000.0,4.886057,p1884,p1884 mol:protein length:168 Dihydrofolate red...,MTKKIVAIWAQDEEGVIGKENRLPWHLPAELQHFKETTLNHAILMG...,Dihydrofolate reductase,"[10, 16, 8, 8, 7, 17, 0, 7, 18, 0, 13, 2, 3, 3..."
4,CCOC(=O)c1oc2cccc(OCC(O)CNC(C)C)c2c1C,Glycylpeptide N-tetradecanoyltransferase,1900.0,5.721246,p50001940,p50001940 mol:protein length:410 Glycylpeptide...,MNDDNKEFSGRDIYQLIKNAKDKIKIDYKFWYTQPVPKINDEFNES...,Glycylpeptide N-tetradecanoyltransferase,"[10, 11, 2, 2, 11, 8, 3, 4, 15, 5, 14, 2, 7, 1..."

In [17]:
len(sample_df.iloc[0]["ProteinTokens"])

512

In [18]:
sample_df.to_pickle("../data/processed/pharmagpt_train.pkl")

print(sample_df.shape)

(5000, 9)

In [19]:
import torch

from torch.utils.data import Dataset

from rdkit import Chem

from torch_geometric.data import Data

In [20]:
def smiles_to_graph(smiles):

    mol = Chem.MolFromSmiles(smiles)

    if mol is None:
        return None

    x = []

    for atom in mol.GetAtoms():

        x.append([
            atom.GetAtomicNum()
        ])

    edges = []

    for bond in mol.GetBonds():

        i = bond.GetBeginAtomIdx()
        j = bond.GetEndAtomIdx()

        edges.append([i, j])
        edges.append([j, i])

    if len(edges) == 0:
        return None

    return Data(
        x=torch.tensor(
            x,
            dtype=torch.float
        ),

        edge_index=torch.tensor(
            edges,
            dtype=torch.long
        ).t()
    )

In [21]:
class PharmaGPTDataset(Dataset):

    def __init__(self, df):

        self.df = df

    def __len__(self):

        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        graph = smiles_to_graph(
            row["Ligand SMILES"]
        )

        protein = torch.tensor(
            row["ProteinTokens"],
            dtype=torch.long
        )

        label = torch.tensor(
            row["pKi"],
            dtype=torch.float
        )

        return (
            graph,
            protein,
            label
        )

In [22]:
dataset = PharmaGPTDataset(
    sample_df
)

print(
    len(dataset)
)

5000

In [23]:
graph, protein, label = dataset[0]

print(graph)
print()

print(protein.shape)

print()

print(label)

Data(x=[16, 1], edge_index=[2, 34])

torch.Size([512])

tensor(7.9208)

In [24]:
from torch_geometric.nn import (
    GCNConv,
    global_mean_pool
)

import torch.nn as nn
import torch

In [25]:
class DrugEncoder(nn.Module):

    def __init__(self):

        super().__init__()

        self.conv1 = GCNConv(1, 64)

        self.conv2 = GCNConv(64, 128)

    def forward(
        self,
        x,
        edge_index,
        batch
    ):

        x = self.conv1(
            x,
            edge_index
        )

        x = torch.relu(x)

        x = self.conv2(
            x,
            edge_index
        )

        x = torch.relu(x)

        return global_mean_pool(
            x,
            batch
        )

In [ ]:
class ProteinEncoder(nn.Module):

    def __init__(self):

        super().__init__()

        self.embedding = nn.Embedding(20,128)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=128,
            nhead=8,
            batch_first=True
        )

        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=2
        )

    def forward(self,x):

        x = self.embedding(x)

        x = self.transformer(x)

        return x.mean(dim=1)

In [43]:
class PharmaGPT(nn.Module):

    def __init__(self):

        super().__init__()

        self.drug_encoder = DrugEncoder()

        self.protein_encoder = ProteinEncoder()

        self.head = nn.Sequential(

            nn.Linear(256,128),

            nn.ReLU(),

            nn.Linear(128,1)
        )

    def forward(
    self,
    graph,
    protein,
    batch
):

        drug_emb = self.drug_encoder(
        graph.x,
        graph.edge_index,
        batch
    )

        protein_emb = self.protein_encoder(
        protein
    )

        x = torch.cat(
        [
            drug_emb,
            protein_emb
        ],
        dim=1
    )

        return self.head(x)

In [44]:
model = PharmaGPT()

print(model)

PharmaGPT(
  (drug_encoder): DrugEncoder(
    (conv1): GCNConv(1, 64)
    (conv2): GCNConv(64, 128)
  )
  (protein_encoder): ProteinEncoder(
    (embedding): Embedding(20, 128)
    (transformer): TransformerEncoder(
      (layers): ModuleList(
        (0-1): 2 x TransformerEncoderLayer(
          (self_attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=128, out_features=128, bias=True)
          )
          (linear1): Linear(in_features=128, out_features=2048, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
          (linear2): Linear(in_features=2048, out_features=128, bias=True)
          (norm1): LayerNorm((128,), eps=1e-05, elementwise_affine=True, bias=True)
          (norm2): LayerNorm((128,), eps=1e-05, elementwise_affine=True, bias=True)
          (dropout1): Dropout(p=0.1, inplace=False)
          (dropout2): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (head): Sequential(
    (0): Linear(in_features=256, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=1, bias=True)
  )
)

In [45]:
graph, protein, label = dataset[0]

protein = protein.unsqueeze(0)

print(protein.shape)

torch.Size([1, 512])

In [46]:
batch = torch.zeros(
    graph.num_nodes,
    dtype=torch.long
)

In [47]:
drug_emb = model.drug_encoder(
    graph.x,
    graph.edge_index,
    batch
)

print(drug_emb.shape)

torch.Size([1, 128])

In [48]:
protein_emb = model.protein_encoder(
    protein
)

print(protein_emb.shape)

torch.Size([1, 128])

In [49]:
prediction = model(
    graph,
    protein,
    batch
)

print(prediction.shape)
print(prediction)

torch.Size([1, 1])
tensor([[-0.0313]], grad_fn=<AddmmBackward0>)

In [50]:
model = PharmaGPT()

In [51]:
graph, protein, label = dataset[0]

protein = protein.unsqueeze(0)

batch = torch.zeros(
    graph.num_nodes,
    dtype=torch.long
)

prediction = model(
    graph,
    protein,
    batch
)

print(prediction.shape)
print(prediction)

torch.Size([1, 1])
tensor([[-0.0872]], grad_fn=<AddmmBackward0>)